auto/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include("portfolio.urls")),
    path('fixweb/', include("fixweb.urls"))
]

fixweb/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views

app_name = "fixweb"

# Django admin header customization

admin.site.site_header = "Auto & Fix Mechanical Breakdown System"
admin.site.site_title = "Welcome Auto & Fix system"
admin.site.index_title = "Auto & Fix Portal"

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("products", views.products, name="products"),
    path("contact", views.contact, name="contact")
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include 
from portfolio import views

urlpatterns = [
    path('', views.portfolio, name='portfolio'),
    path('about', views.about, name='about'),
    path('projects', views.projects, name='projects'),
    path('contact', views.contact, name='Contact')
]

fixweb/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    first = models.CharField(max_length=30)
    last = models.CharField(max_length=30)
    email = models.EmailField()
    phone = models.CharField(max_length=8)
    message = models.TextField(max_length=30)

    def __str__(self):
        return self.first + " , " + self.last + " , " + self.email + " , " + self.phone + " , " + self.message

portfolio/models.py
from django.db import models

# Create your models here.

fixweb/views.py
from django.shortcuts import render
from fixweb.models import Contact

# Create your views here.
def index(request):
    return render(request,"fixweb/index.html")

def about(request):
    return render(request,"fixweb/about.html")

def products(request):
    return render(request,"fixweb/products.html")

def contact(request):
    if request.method == "POST":

        first = request.POST['first']
        last = request.POST['last']
        email = request.POST['email']
        phone = request.POST['phone']
        message = request.POST['message']

        ins = Contact(first=first, last=last, email=email, phone=phone, message=message)
        ins.save()

        print("Successfully saved to the DB.")

    return render(request,"fixweb/contact.html")

portfolio/views.py
from django.shortcuts import render, HttpResponse 

# Create your views here.
def portfolio(request):
    return render(request,'index.html')

def about(request):
    return render(request,'about.html')

def projects(request):
    return render(request,'projects.html')

def contact(request):
    return render(request,'contact.html')

fixweb/templates/fixweb/about.html
{% extends "fixweb/layout.html" %}

{% block body %}
<div class="container my-4">
    <h4>About Us</h4>
    <p>Auto & Fix Mechanical Breakdown is a company established in 2021. Amet laboris in ut qui. Nulla cillum amet
        reprehenderit elit est sunt velit. Dolore in aute excepteur quis aliquip cupidatat esse consectetur. </p>
    
    <h4>Our Team</h4>
    <p>Irure nisi ea reprehenderit nulla non elit culpa amet aute. Laborum adipisicing nulla cupidatat sunt mollit qui ea. Elit dolor mollit voluptate duis.</p>

    <h4>Our Partners</h4>
    <p>Sint duis laboris exercitation mollit pariatur commodo labore enim eu exercitation officia do Lorem reprehenderit. Minim Lorem exercitation reprehenderit ad enim consectetur consequat laboris in ut ex. Ullamco duis proident laboris et proident amet et sit id nostrud fugiat nulla. Amet magna in magna in non. Lorem nulla excepteur ea Lorem cillum ex eu irure qui aliqua sint.</p>


</div>

{% endblock %}

fixweb/templates/fixweb/contact.html
{% extends "fixweb/layout.html" %}

{% block body %}
<div class="container-fluid mt-3">
  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
        aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
        aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
        aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://source.unsplash.com/900x100/?car,accident" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://source.unsplash.com/900x100/?mechanic,carparts" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://source.unsplash.com/900x100/?breakdown,workshop" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
      data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
      data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>
<div class="container my-4">
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Contact details</h5>
          <p class="card-text">Phone:</p>
          <p class="card-text">2233 3223</p>
          <p class="card-text">Email:</p>
          <p class="card-text">sales@autoandfix.com</p>
          <p class="card-text">Physical address:</p>
          <p class="card-text">Marabeng,Main North 1, Next to Puma Garage, Berea 200, Lesotho</p>

        </div>

        <div class="container-fluid">
          <div class="map-responsive">
            <iframe
              src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA0s1a7phLN0iaD6-UE7m4qP-z21pH0eSc&q=Eiffel+Tower+Paris+France"
              width="400" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
          </div>
        </div>
      </div>
     
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Send us an email:</h5>
          <form action="/fixweb/contact" method="POST">
            {% csrf_token %}
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">First name</label>
              <input type="text" class="form-control" id="first" name="first">
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Last Name</label>
              <input type="text" class="form-control" id="last" name="last">
            </div>
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Email address</label>
              <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
              <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Phone number</label>
              <input type="phone" class="form-control" id="phone" name="phone">
            </div>
            <div class="mb-3">
              <label for="exampleFormControlTextarea1" class="form-label">Message</label>
              <textarea class="form-control" id="mesage" name="message" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

fixweb/templates/fixweb/index.html
{% extends "fixweb/layout.html" %}

{% block body %}
<div class="container-fluid mt-3">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="https://source.unsplash.com/900x200/?car,accident" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://source.unsplash.com/900x200/?mechanic,carparts" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://source.unsplash.com/900x200/?breakdown,workshop" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

<div class="container mt-3">
    <h4>What we offer in summary</h4>
    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne"
                    aria-expanded="true" aria-controls="collapseOne">
                    Mechanic plans
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
                data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <strong>This is the first item's accordion body.</strong> It is hidden by default, until the
                    collapse plugin adds the appropriate classes that we use to style each element. These classes
                    control the overall appearance, as well as the showing and hiding via CSS transitions. You can
                    modify any of this with custom CSS or overriding our default variables. It's also worth noting that
                    just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit
                    overflow.
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Cash back Plus
                </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
                data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <strong>With Cash Back Plus, we give you cash back if you do not claim. If you
                        remain claim-free for ve uninterrupted years, then you will be entitled
                        to a pay-out of your entire rst year's contributions.</strong> It is hidden by default, until
                    the collapse plugin adds the appropriate classes that we use to style each element. These classes
                    control the overall appearance, as well as the showing and hiding via CSS transitions. You can
                    modify any of this with custom CSS or overriding our default variables. It's also worth noting that
                    just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit
                    overflow.
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Contribution Waiver
                </button>
            </h2>
            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
                data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <strong>A premium waiver will be activated upon the death of a principal
                        member. All the vehicles under the plan will remain covered for the next
                        6 months. Cover termination age is 65 years.</strong> It is hidden by default, until the
                    collapse plugin adds the appropriate classes that we use to style each element. These classes
                    control the overall appearance, as well as the showing and hiding via CSS transitions. You can
                    modify any of this with custom CSS or overriding our default variables. It's also worth noting that
                    just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit
                    overflow.
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Funeral Benefit
                </button>
            </h2>
            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
                data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <strong>Auto & Fix Mechanical Breakdown member is automatically legible for
                        funeral benets under their selected option. Immediately upon death,
                        Auto & Fix Mechanical Breakdown will pay a lump sum of cash benet as
                        stipulated by your chosen option.</strong> It is hidden by default, until the collapse plugin
                    adds the appropriate classes that we use to style each element. These classes control the overall
                    appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with
                    custom CSS or overriding our default variables. It's also worth noting that just about any HTML can
                    go within the <code>.accordion-body</code>, though the transition does limit overflow.
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

fixweb/templates/fixweb/layout.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <link href="{% static 'fixweb/styles.css' %}" rel="stylesheet">
    <title>Home</title>
</head>

<body>
    <div class="container-fluid">
        <header
            class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-body border-bottom shadow-sm">
            <p class="h5 my-0 me-md-auto fw-normal"><img src="{% static 'fixweb/images/log.png' %}" alt="" width="403" height="154"></p>
            <nav class="my-2 my-md-0 me-md-3">
                <a class="p-2 text-dark" href="{% url 'fixweb:index'%}">Home</a>
                <a class="p-2 text-dark" href="{% url 'fixweb:about' %}">About</a>
                <a class="p-2 text-dark" href="{% url 'fixweb:products' %}">Products</a>
                <a class="p-2 text-dark" href="{% url 'fixweb:contact' %}">Contact us</a>
            </nav>
        </header>
    </div>
    {% block body %}

    {% endblock %}
    <div class="container pt-4 my-md-5 pt-md-5 border-top imgBackground">
        <footer>
            <div class="row">
                <div class="col-6 col-md">
                    <h5>Services</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="link-secondary" href="#">Mechanical services</a></li>
                        <li><a class="link-secondary" href="#">Other services</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Social media</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="link-secondary" href="#">Facebook</a></li>
                        <li><a class="link-secondary" href="#">Twitter</a></li>
                        <li><a class="link-secondary" href="#">Linkedin</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>About</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="link-secondary" href="#">Team</a></li>
                        <li><a class="link-secondary" href="#">Locations</a></li>
                        <li><a class="link-secondary" href="#">Privacy</a></li>
                        <li><a class="link-secondary" href="#">Terms</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
            -->
</body>

</html>

fixweb/templates/fixweb/products.html
{% extends "fixweb/layout.html" %}

{% block body %}
<div class="container my-3">
    <h4>Our services</h4>

    <div class="accordion accordion-flush" id="accordionFlushExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                    Mechanical Plan Benefits
                </button>
            </h2>
            <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Cmponents</th>
                                <th scope="col">Machane</th>
                                <th scope="col">Mankhoe</th>
                                <th scope="col">Tobaka</th>
                                <th scope="col">Thabure</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>
                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>
                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>
                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>
                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>
                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>
                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                            <tr>
                                <td>Engine</td>
                                <td>7,631</td>
                                <td>12,718</td>
                                <td>17,800</td>
                                <td>12,718</td>

                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                    CASH BACK PLUS
                </button>
            </h2>
            <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo"
                data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">With Cash Back Plus, we give you cash back if you do not claim. If you
                    remain claim-free for ve uninterrupted years, then you will be entitled
                    to a pay-out of your entire rst year's contributions.</div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                    CONTRIBUTION WAIVER
                </button>
            </h2>
            <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree"
                data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">A premium waiver will be activated upon the death of a principal
                    member. All the vehicles under the plan will remain covered for the next
                    6 months. Cover termination age is 65 years.</div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                    FUNERAL BENEFIT
                </button>
            </h2>
            <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree"
                data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">Auto & Fix Mechanical Breakdown member is automatically legible for
                    funeral benets under their selected option. Immediately upon death,
                    Auto & Fix Mechanical Breakdown will pay a lump sum of cash benet as
                    stipulated by your chosen option.</div>
            </div>
        </div>
    </div>
</div>

{% endblock %}